packages:
  wmbus_gateway: github://IoTLabs-pl/wM-Bus-Gateway/packages/wmbus_gateway.yaml@master

esphome:
  name: wmbus-gateway
  comment: wM-Bus Gateway for ESPHome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

wmbus_meter:
  # This part of config is responsible for handling the received frames
  # for the specified meter. You may send whole decoded datagram everywhere
  # You may specify multiple meters.
  - id: my_meter
    meter_id: 123456789
    type: apator162
    key: SomeKey # Optional, if your meter is encrypted. May be specified as ASCII or HEX string.
    # mode: C1 # or T1 if you want to filter specific modes. When not specified, all modes are accepted.
    # on_telegram:
    # Sending telegram to MQTT topic as JSON. MQTT component must be configured in your config.
    #   - then: 
    #       - wmbus_meter.send_telegram_with_mqtt:
    #           topic: some_topic
    # Sending telegram to HTTP endpoint as JSON.
    #   - then:
    #       - http_request.post:
    #           url: http://example.com/api
    #           headers:
    #             Content-Type: application/json
    #           body: !lambda |-
    #             return meter.as_json();

sensor:
  # This part of config is responsible for extracting specific fields
  # from the meter data and making them available as sensors.
  # By default, unit of measurement is determined from the field.
  # You may specify unit of measurement to override it.
  # All parameters from https://esphome.io/components/sensor/index.html are supported.
  - platform: wmbus_meter
    id: total_water_sensor
    field: total_m3
    parent_id: my_meter
    name: Water Consumption
    state_class: total_increasing
    device_class: water
  - platform: wmbus_meter
    id: water_meter_rssi
    field: rssi_dbm
    parent_id: my_meter
    name: RSSI
    device_class: signal_strength
    state_class: measurement

# If you want to set specific pages on the display, you may use the following config.
# By default, all defined sensor are displayed.
wmbus_gateway_gui:
  pages:
    - total_water_sensor
    - water_meter_rssi

