## This file is used to automated build check on GitHub Actions.

esphome:
  name: test

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source: ./components

wifi:
  ssid: TestSSID
  password: TestPass

mqtt:
  broker: 192.168.1.1
  port: 1883

spi:
  clk_pin: GPIO0
  mosi_pin: GPIO1
  miso_pin: GPIO2

socket_transmitter:
  id: test_transmitter
  ip_address: 192.168.1.1
  port: 12345
  protocol: TCP

wmbus_common:
  drivers: all

wmbus_radio:
  radio_type: SX1276
  cs_pin: GPIO3
  reset_pin: GPIO4
  irq_pin: GPIO5
  on_frame:
    - wmbus_radio.send_frame_with_socket:
        id: test_transmitter
        format: rtlwmbus

wmbus_meter:
  id: test_meter
  meter_id: "12345678"
  type: apator162
  on_telegram:
    - wmbus_meter.send_telegram_with_mqtt:
        topic: test_topic

sensor:
  - platform: wmbus_meter
    id: test_sensor
    parent_id: test_meter
    field: total_m3
    name: "Test Water Consumption"

