#!/usr/bin/env python3
"""Fetch a wmbusmeters ref into components/wmbus_common: drivers/src/*.xmq and tables/*.yaml.

Nothing is committed: review the diff. --diff instead prints upstream's log and diff from the recorded ref.
"""

import argparse
import contextlib
import io
import math
import re
import subprocess
import sys
import tarfile
import tempfile
from pathlib import Path

import yaml

COMPONENT_DIR = Path(__file__).resolve().parents[2] / "components" / "wmbus_common"
DRIVERS_DIR = COMPONENT_DIR / "drivers" / "src"
LIBRARY_FILE = COMPONENT_DIR / "drivers" / "library.xmq"
TABLES_DIR = COMPONENT_DIR / "tables"
TAG_FILE = COMPONENT_DIR / ".wmbusmeters_tag"
UPSTREAM_URL = "https://github.com/wmbusmeters/wmbusmeters.git"
# The C++ this component ports; drivers and tables show up in our own diff.
DIFF_PATHS = ("src",)

# HZ is a macro in the ESP32-C3 toolchain's sys/param.h.
RENAMED_UNITS = {"HZ": "Hertz"}


def unit_name(cname: str) -> str:
    return RENAMED_UNITS.get(cname, cname)


# SIExp's setters in units.h; unixTimestamp() is spelled out, the rest are the keys.
EXPONENT_KEYS = ("s", "m", "kg", "a", "mol", "cd", "k", "c", "f", "month", "year", "ut")
_SETTER_TO_KEY = {**{k: k for k in EXPONENT_KEYS}, "unixTimestamp": "ut"}


def macro_entries(text: str, macro: str) -> list[str]:
    start = text.index(f"#define {macro}")
    end = text.index("\n\n", start)
    body = text[start:end]
    entries = []
    pos = 0
    while True:
        pos = body.find("X(", pos)
        if pos < 0:
            break
        depth = 0
        i = pos + 1
        while True:
            if body[i] == "(":
                depth += 1
            elif body[i] == ")":
                depth -= 1
                if depth == 0:
                    break
            i += 1
        entries.append(body[pos + 2 : i])
        pos = i
    return entries


def parse_quantities(units_h: str) -> dict[str, str]:
    result = {}
    for entry in macro_entries(units_h, "LIST_OF_QUANTITIES"):
        quantity, unit = [p.strip() for p in entry.split(",")]
        result[quantity] = unit_name(unit)
    return result


def eval_scale(expr: str) -> float:
    if not re.fullmatch(r"[0-9.eE+\-*/ M_PI()]+", expr):
        sys.exit(f"unexpected scale expression in units.cc: {expr!r}")
    return float(eval(expr, {"__builtins__": {}}, {"M_PI": math.pi}))  # noqa: S307


def si_exponents(chain: str) -> dict:
    """SIExp().kg(1).m(2).s(-2) -> {kg: 1, m: 2, s: -2}, plus nonlinear when flagged."""
    exps = {}
    for name, args in re.findall(r"\.(\w+)\(([^()]*)\)", chain):
        if name == "nonlinear":
            exps["nonlinear"] = True
        else:
            exps[_SETTER_TO_KEY[name]] = int(args)
    return exps


def parse_units(units_h: str, units_cc: str) -> dict[str, dict]:
    si = {}
    for entry in macro_entries(units_cc, "LIST_OF_SI_CONVERSIONS"):
        cname, rest = entry.split(",", 1)
        scale_text, chain = rest.split("SIExp()", 1)
        scale_text = re.sub(r"/\*.*?\*/", "", scale_text).strip().rstrip(",").strip()
        si[cname.strip()] = {"scale": eval_scale(scale_text), **si_exponents(chain)}

    units = {}
    for entry in macro_entries(units_h, "LIST_OF_UNITS"):
        cname, lcname, hrname, quantity, _explanation = [p.strip() for p in entry.split(",", 4)]
        unit = {"symbol": lcname, "display": hrname.strip('"'), "quantity": quantity}
        if cname in si:
            unit["si"] = si[cname]
        units[unit_name(cname)] = unit
    return units


class Hex(int):
    """Written as 0x.., which YAML reads back as the same int."""


def parse_vif_ranges(dvparser_h: str) -> dict[str, dict]:
    result = {}
    for entry in macro_entries(dvparser_h, "LIST_OF_VIF_RANGES"):
        name, low, high, _quantity, unit = [p.strip() for p in entry.split(",")]
        result[name] = {"from": Hex(low, 0), "to": Hex(high, 0), "unit": unit_name(unit.removeprefix("Unit::"))}
    return result


def parse_vif_combinables(dvparser_h: str) -> dict[str, dict]:
    result = {}
    for entry in macro_entries(dvparser_h, "LIST_OF_VIF_COMBINABLES"):
        name, low, high = [p.strip() for p in entry.split(",")]
        result[name] = {"from": Hex(low, 0), "to": Hex(high, 0)}
    return result


class _Dumper(yaml.SafeDumper):
    pass


_Dumper.add_representer(Hex, lambda dumper, v: dumper.represent_scalar("tag:yaml.org,2002:int", f"0x{v:02x}"))


def write_tables(ref: str, units_h: str, units_cc: str, dvparser_h: str) -> dict[str, int]:
    TABLES_DIR.mkdir(exist_ok=True)
    tables = {
        "quantities": parse_quantities(units_h),
        "units": parse_units(units_h, units_cc),
        "vif_ranges": parse_vif_ranges(dvparser_h),
        "vif_combinables": parse_vif_combinables(dvparser_h),
    }
    header = f"# Generated by scripts/wmbus_common/fetch_upstream.py from wmbusmeters {ref}; do not edit.\n"
    for name, data in tables.items():
        body = yaml.dump(data, Dumper=_Dumper, sort_keys=False, allow_unicode=True)
        (TABLES_DIR / f"{name}.yaml").write_text(header + body, encoding="utf-8")
    return {name: len(data) for name, data in tables.items()}


@contextlib.contextmanager
def upstream():
    """A throwaway blobless clone: ~2.5 MB and a second, and never a stale ref."""
    with tempfile.TemporaryDirectory() as tmp:
        repo = Path(tmp) / "wmbusmeters.git"
        subprocess.run(
            ["git", "clone", "--quiet", "--bare", "--filter=blob:none", UPSTREAM_URL, str(repo)],
            check=True,
        )

        def git(*args: str, binary: bool = False, quiet: bool = False):
            done = subprocess.run(
                ["git", "-C", str(repo), *args],
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.DEVNULL if quiet else None,
            )
            return done.stdout if binary else done.stdout.decode().strip()

        yield git


def describe(git, ref: str) -> str:
    """What a ref resolves to: 3.0.0, or 3.0.0-106-gce0ced0 past that tag."""
    try:
        return git("describe", "--tags", ref, quiet=True)
    except subprocess.CalledProcessError:
        sys.exit(f"no such ref in wmbusmeters: {ref}")


def show_diff(git, ref: str, paths: list[str]) -> None:
    old = TAG_FILE.read_text().strip()
    new = describe(git, ref)
    if old == new:
        print(f"wmbusmeters {new}: already the recorded ref")
        return
    print(f"wmbusmeters {old} -> {new}, over {' '.join(paths)}\n")
    for command in (("log", "--oneline", "--no-decorate"), ("diff",)):
        # Going backwards to an older ref leaves the log empty.
        if output := git(*command, f"{old}..{new}", "--", *paths):
            print(output + "\n")


def fetch(git, ref: str) -> None:
    new = describe(git, ref)
    for old in DRIVERS_DIR.glob("*.xmq"):
        old.unlink()
    if LIBRARY_FILE.exists():
        LIBRARY_FILE.unlink()
    drivers = 0
    archive = tarfile.open(fileobj=io.BytesIO(git("archive", new, "--", "drivers", binary=True)))
    for member in archive.getmembers():
        if not member.isfile() or not member.name.endswith(".xmq"):
            continue
        content = archive.extractfile(member).read()
        if member.name == "drivers/library.xmq":
            LIBRARY_FILE.write_bytes(content)
        elif member.name.startswith("drivers/src/"):
            text = content.decode("utf-8", errors="replace")
            # Skip drivers deprecated at the driver level (before fields {)
            fields_pos = text.find("fields {")
            head = text[:fields_pos] if fields_pos > 0 else text
            if re.search(r"^\s*deprecated_by\s*=", head, re.MULTILINE):
                continue
            (DRIVERS_DIR / Path(member.name).name).write_bytes(content)
            drivers += 1

    def text(relpath: str) -> str:
        return git("show", f"{new}:{relpath}")

    counts = write_tables(new, text("src/units.h"), text("src/units.cc"), text("src/dvparser.h"))
    TAG_FILE.write_text(new + "\n")
    print(f"wmbusmeters {new}: {drivers} drivers, " + ", ".join(f"{n} {k}" for k, n in counts.items()))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("ref", help="tag, branch or commit of wmbusmeters")
    parser.add_argument(
        "--diff",
        action="store_true",
        help="print upstream's history and diff from the recorded ref instead of fetching",
    )
    parser.add_argument(
        "paths", nargs="*", help=f"what --diff covers (default: {' '.join(DIFF_PATHS)})"
    )
    args = parser.parse_args()
    if args.paths and not args.diff:
        parser.error("paths only mean something with --diff")

    with upstream() as git:
        if args.diff:
            show_diff(git, args.ref, args.paths or list(DIFF_PATHS))
        else:
            fetch(git, args.ref)


if __name__ == "__main__":
    main()
