packages:
  core: !include
    file: wmbus_gateway_core.yaml

button:
  - platform: restart
    name: Restart

debug:
  update_interval: 15s

sensor:
  - platform: uptime
    type: timestamp
    name: Uptime
    disabled_by_default: True
  - platform: wifi_signal
    name: RSSI
    update_interval: 60s
    disabled_by_default: True
  - platform: debug
    free:
      name: Free Heap
      device_class: data_size
      disabled_by_default: True
      state_class: measurement

